export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES2 = "FETCH_COURSES2";
export const FETCH_COURSES3 = "FETCH_COURSES3";
export const FETCH_COURSES4 = "FETCH_COURSES4";
export const FETCH_COURSES_DETAIL = "FETCH_COURSES_DETAIL";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";

export const ADD_TO_CART = "ADD_TO_CART";